# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, 8.1'
pod 'GoogleMaps'

target 'ParkDetroit' do

end

target 'ParkDetroitTests' do

end

target 'ParkDetroitUITests' do

end

